-   id: luzfcb/spectral
    name: luzfcb/spectral
    entry: spectral lint
    language: node
    'files': (openapi|swagger)(2|3|)((\.[0-9])|)\.(yaml|json)$
    args: []
    require_serial: true
    additional_dependencies: ["@luzfcb/spectral@4.2.1-beta1"]
